[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/adoptions-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[variables]
SPRING_PROFILES_ACTIVE = "production"
PORT = "8080"