services:
  - type: web
    name: adoptions-api
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/adoptions-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        fromService:
          type: web
          name: adoptions-api
          property: port